/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Indralaya.UI;

import Indralaya.Core.*;
import au.com.bytecode.opencsv.CSVReader;
import java.awt.*;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.List;

/**
 *
 * @author Rin Nadia
 */
public class FirstUI extends javax.swing.JFrame {

    /**
     * Creates new form FirstUI
     */
    /*InputParameterUI2 subFrame;
     InputParameterUI inputForm;*/
    CardLayout card;
    DefaultTableModel DftTabMode;
    JFileChooser pemilih;
    FileNameExtensionFilter saringan;
    CSVReader pembaca;
    String[] strings;
    String alamatFile, lr, me;
    double learningRate, minimumError;
    ButtonGroup groupLR, groupME;
    int banyakData, i, n, m;
    MainController objekMC;

    public FirstUI() {

        initComponents();
        getContentPane().setBackground(Color.BLACK);
        //Untuk Memilih File
        card = (CardLayout) panelUtama.getLayout();
        pemilih = new JFileChooser();
        saringan = new FileNameExtensionFilter("CSV Format Only", "csv");
        pemilih.setFileFilter(saringan);
        //Untuk button group parameter
        groupLR = new ButtonGroup();
        groupME = new ButtonGroup();

        groupLR.add(jLajuPem1);
        groupLR.add(jLajuPem2);
        groupLR.add(jLajuPem3);

        groupME.add(jToleKe1);
        groupME.add(jToleKe2);
        groupME.add(jToleKe3);

        //Tabbeb Pane Utama
        /*JComponent panel1 = makeTextPanel("Panel #1");
         tabbebPaneHasil.addTab("Pembelajaran Pertama", rootPane);
        
         tabbebPaneHasil.addTab("Pangkas Neuron", rootPane);
         tabbebPaneHasil.addTab("Pembelajaran Kedua", rootPane);
         tabbebPaneHasil.addTab("Discretizing", rootPane);
         tabbebPaneHasil.addTab("Pembelajaran Ketiga", rootPane);
         tabbebPaneHasil.addTab("Clustering", rootPane);
         tabbebPaneHasil.addTab("Aturan", rootPane);
         add(tabbebPaneHasil);*/
        //objekMC = new MainController();
        /*int a = 0; double b = 0.5;
         textAreaPemPertama.append("test");
         textAreaPemPertama.
         textAreaPemPertama.append("Epoch = " + a +", Error = "+b);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelUtama = new javax.swing.JPanel();
        panelTrainingEkstrak = new javax.swing.JPanel();
        labelJudulPanelEkstrak = new javax.swing.JLabel();
        Discretizing = new javax.swing.JTabbedPane();
        panelPemPertama = new javax.swing.JPanel();
        textFieldTotalEpoch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPemPertama = new javax.swing.JTextArea();
        panelPangkasNeuron = new javax.swing.JPanel();
        textFieldPruning1 = new javax.swing.JTextField();
        textFieldPruning2 = new javax.swing.JTextField();
        textFieldPruning3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaPruning = new javax.swing.JTextArea();
        panelPemKedua = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        textAreaBobotOutput = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        textAreaNilaiAktivasi = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        textAreaBobotBias = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        textAreaPemKedua = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        panelDiscretizing = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaPemDiscretize = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaDiscretize = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        panelAturan = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaAturan = new javax.swing.JTextArea();
        panelParameter = new javax.swing.JPanel();
        labelJudulPanelPatameter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldAlamatDataset = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLajuPem1 = new javax.swing.JRadioButton();
        jLajuPem2 = new javax.swing.JRadioButton();
        jLajuPem3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jToleKe1 = new javax.swing.JRadioButton();
        jToleKe2 = new javax.swing.JRadioButton();
        jToleKe3 = new javax.swing.JRadioButton();
        buttonOk1 = new javax.swing.JButton();
        buttonReset1 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        panelTitle = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        labelPanelUtama = new javax.swing.JLabel();
        fieldPetunjukAplikasi = new javax.swing.JTextField();
        buttonParameter = new javax.swing.JButton();
        buttonEkstrak = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        labelPetunjukDataset = new javax.swing.JLabel();
        textFieldDataSet = new javax.swing.JTextField();
        labelPetunjukLajuPembelajaran = new javax.swing.JLabel();
        textFieldLearningRate = new javax.swing.JTextField();
        labelPetunjukMinimumError = new javax.swing.JLabel();
        textFieldMinimumError = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        panelUtama.setBackground(new java.awt.Color(113, 167, 60));
        panelUtama.setPreferredSize(new java.awt.Dimension(1163, 634));
        panelUtama.setLayout(new java.awt.CardLayout());

        panelTrainingEkstrak.setBackground(new java.awt.Color(113, 167, 60));

        labelJudulPanelEkstrak.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        labelJudulPanelEkstrak.setForeground(new java.awt.Color(255, 255, 255));
        labelJudulPanelEkstrak.setText("Pembelajaran dan Ekstraksi");

        Discretizing.setBackground(new java.awt.Color(234, 137, 69));
        Discretizing.setForeground(new java.awt.Color(234, 137, 69));
        Discretizing.setToolTipText("");
        Discretizing.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Discretizing.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        panelPemPertama.setBackground(new java.awt.Color(234, 137, 69));
        panelPemPertama.setForeground(new java.awt.Color(234, 137, 69));
        panelPemPertama.setToolTipText("");

        textFieldTotalEpoch.setBackground(new java.awt.Color(234, 137, 69));
        textFieldTotalEpoch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        textFieldTotalEpoch.setForeground(new java.awt.Color(255, 255, 255));
        textFieldTotalEpoch.setBorder(null);

        textAreaPemPertama.setBackground(new java.awt.Color(234, 137, 69));
        textAreaPemPertama.setColumns(20);
        textAreaPemPertama.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaPemPertama.setRows(5);
        jScrollPane1.setViewportView(textAreaPemPertama);

        javax.swing.GroupLayout panelPemPertamaLayout = new javax.swing.GroupLayout(panelPemPertama);
        panelPemPertama.setLayout(panelPemPertamaLayout);
        panelPemPertamaLayout.setHorizontalGroup(
            panelPemPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPemPertamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPemPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldTotalEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        panelPemPertamaLayout.setVerticalGroup(
            panelPemPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPemPertamaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textFieldTotalEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        Discretizing.addTab("Pembelajaran Pertama", panelPemPertama);

        panelPangkasNeuron.setBackground(new java.awt.Color(234, 137, 69));

        textFieldPruning1.setBackground(new java.awt.Color(234, 137, 69));
        textFieldPruning1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldPruning1.setForeground(new java.awt.Color(255, 255, 255));
        textFieldPruning1.setBorder(null);

        textFieldPruning2.setBackground(new java.awt.Color(234, 137, 69));
        textFieldPruning2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldPruning2.setForeground(new java.awt.Color(255, 255, 255));
        textFieldPruning2.setBorder(null);

        textFieldPruning3.setBackground(new java.awt.Color(234, 137, 69));
        textFieldPruning3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldPruning3.setForeground(new java.awt.Color(255, 255, 255));
        textFieldPruning3.setBorder(null);

        textAreaPruning.setBackground(new java.awt.Color(234, 137, 69));
        textAreaPruning.setColumns(20);
        textAreaPruning.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaPruning.setRows(5);
        jScrollPane2.setViewportView(textAreaPruning);

        javax.swing.GroupLayout panelPangkasNeuronLayout = new javax.swing.GroupLayout(panelPangkasNeuron);
        panelPangkasNeuron.setLayout(panelPangkasNeuronLayout);
        panelPangkasNeuronLayout.setHorizontalGroup(
            panelPangkasNeuronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPangkasNeuronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPangkasNeuronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPruning1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPruning2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPruning3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        panelPangkasNeuronLayout.setVerticalGroup(
            panelPangkasNeuronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPangkasNeuronLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textFieldPruning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPruning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPruning3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        Discretizing.addTab("Prunning Neuron", panelPangkasNeuron);

        panelPemKedua.setBackground(new java.awt.Color(234, 137, 69));

        textAreaBobotOutput.setBackground(new java.awt.Color(234, 137, 69));
        textAreaBobotOutput.setColumns(20);
        textAreaBobotOutput.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaBobotOutput.setRows(5);
        jScrollPane9.setViewportView(textAreaBobotOutput);

        jLabel5.setBackground(new java.awt.Color(234, 137, 69));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Bobot Bias");

        jLabel6.setBackground(new java.awt.Color(234, 137, 69));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nilai Hasil Aktivasi Lapisan Tersembunyi");

        textAreaNilaiAktivasi.setBackground(new java.awt.Color(234, 137, 69));
        textAreaNilaiAktivasi.setColumns(20);
        textAreaNilaiAktivasi.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaNilaiAktivasi.setRows(5);
        jScrollPane11.setViewportView(textAreaNilaiAktivasi);

        textAreaBobotBias.setBackground(new java.awt.Color(234, 137, 69));
        textAreaBobotBias.setColumns(20);
        textAreaBobotBias.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaBobotBias.setRows(5);
        jScrollPane12.setViewportView(textAreaBobotBias);

        jLabel7.setBackground(new java.awt.Color(234, 137, 69));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Bobot Lapisan Keluaran");

        textAreaPemKedua.setBackground(new java.awt.Color(234, 137, 69));
        textAreaPemKedua.setColumns(20);
        textAreaPemKedua.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaPemKedua.setRows(5);
        jScrollPane13.setViewportView(textAreaPemKedua);

        jLabel8.setBackground(new java.awt.Color(234, 137, 69));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Hasil");

        javax.swing.GroupLayout panelPemKeduaLayout = new javax.swing.GroupLayout(panelPemKedua);
        panelPemKedua.setLayout(panelPemKeduaLayout);
        panelPemKeduaLayout.setHorizontalGroup(
            panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPemKeduaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(panelPemKeduaLayout.createSequentialGroup()
                        .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPemKeduaLayout.setVerticalGroup(
            panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPemKeduaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPemKeduaLayout.createSequentialGroup()
                        .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPemKeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPemKeduaLayout.createSequentialGroup()
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Discretizing.addTab("Pembelajaran Kedua", panelPemKedua);

        panelDiscretizing.setBackground(new java.awt.Color(234, 137, 69));

        textAreaPemDiscretize.setBackground(new java.awt.Color(234, 137, 69));
        textAreaPemDiscretize.setColumns(20);
        textAreaPemDiscretize.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaPemDiscretize.setRows(5);
        jScrollPane5.setViewportView(textAreaPemDiscretize);

        textAreaDiscretize.setBackground(new java.awt.Color(234, 137, 69));
        textAreaDiscretize.setColumns(20);
        textAreaDiscretize.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaDiscretize.setRows(5);
        jScrollPane6.setViewportView(textAreaDiscretize);

        jLabel9.setBackground(new java.awt.Color(234, 137, 69));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Pembelajaran Dengan Menggunakan Nilai Discretize");

        javax.swing.GroupLayout panelDiscretizingLayout = new javax.swing.GroupLayout(panelDiscretizing);
        panelDiscretizing.setLayout(panelDiscretizingLayout);
        panelDiscretizingLayout.setHorizontalGroup(
            panelDiscretizingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscretizingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDiscretizingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDiscretizingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                        .addComponent(jScrollPane6))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        panelDiscretizingLayout.setVerticalGroup(
            panelDiscretizingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiscretizingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Discretizing.addTab("Discretizing", panelDiscretizing);

        panelAturan.setBackground(new java.awt.Color(234, 137, 69));

        textAreaAturan.setBackground(new java.awt.Color(234, 137, 69));
        textAreaAturan.setColumns(20);
        textAreaAturan.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textAreaAturan.setRows(5);
        jScrollPane7.setViewportView(textAreaAturan);

        javax.swing.GroupLayout panelAturanLayout = new javax.swing.GroupLayout(panelAturan);
        panelAturan.setLayout(panelAturanLayout);
        panelAturanLayout.setHorizontalGroup(
            panelAturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        panelAturanLayout.setVerticalGroup(
            panelAturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAturanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        Discretizing.addTab("Aturan", panelAturan);

        javax.swing.GroupLayout panelTrainingEkstrakLayout = new javax.swing.GroupLayout(panelTrainingEkstrak);
        panelTrainingEkstrak.setLayout(panelTrainingEkstrakLayout);
        panelTrainingEkstrakLayout.setHorizontalGroup(
            panelTrainingEkstrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainingEkstrakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrainingEkstrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudulPanelEkstrak)
                    .addComponent(Discretizing, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        panelTrainingEkstrakLayout.setVerticalGroup(
            panelTrainingEkstrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainingEkstrakLayout.createSequentialGroup()
                .addComponent(labelJudulPanelEkstrak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Discretizing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUtama.add(panelTrainingEkstrak, "card2");

        panelParameter.setBackground(new java.awt.Color(113, 167, 60));

        labelJudulPanelPatameter.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelJudulPanelPatameter.setForeground(new java.awt.Color(255, 255, 255));
        labelJudulPanelPatameter.setText("Input Parameter dan Dataset");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dataset Masukan");

        fieldAlamatDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatDatasetActionPerformed(evt);
            }
        });

        buttonCari.setBackground(new java.awt.Color(255, 255, 255));
        buttonCari.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(0, 141, 47));
        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Laju Pembelajaran");

        jLajuPem1.setBackground(new java.awt.Color(113, 167, 60));
        jLajuPem1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLajuPem1.setForeground(new java.awt.Color(255, 255, 255));
        jLajuPem1.setText("0.1");

        jLajuPem2.setBackground(new java.awt.Color(113, 167, 60));
        jLajuPem2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLajuPem2.setForeground(new java.awt.Color(255, 255, 255));
        jLajuPem2.setText("0.3");

        jLajuPem3.setBackground(new java.awt.Color(113, 167, 60));
        jLajuPem3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLajuPem3.setForeground(new java.awt.Color(255, 255, 255));
        jLajuPem3.setText("0.5");
        jLajuPem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLajuPem3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Toleransi Kesalahan");

        jToleKe1.setBackground(new java.awt.Color(113, 167, 60));
        jToleKe1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToleKe1.setForeground(new java.awt.Color(255, 255, 255));
        jToleKe1.setText("0.1");

        jToleKe2.setBackground(new java.awt.Color(113, 167, 60));
        jToleKe2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToleKe2.setForeground(new java.awt.Color(255, 255, 255));
        jToleKe2.setText("0.3");

        jToleKe3.setBackground(new java.awt.Color(113, 167, 60));
        jToleKe3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jToleKe3.setForeground(new java.awt.Color(255, 255, 255));
        jToleKe3.setText("0.5");

        buttonOk1.setBackground(new java.awt.Color(255, 255, 255));
        buttonOk1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonOk1.setForeground(new java.awt.Color(0, 141, 47));
        buttonOk1.setText("OK");
        buttonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOk1ActionPerformed(evt);
            }
        });

        buttonReset1.setBackground(new java.awt.Color(255, 255, 255));
        buttonReset1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonReset1.setForeground(new java.awt.Color(0, 141, 47));
        buttonReset1.setText("Batal");
        buttonReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReset1ActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tabelData);

        javax.swing.GroupLayout panelParameterLayout = new javax.swing.GroupLayout(panelParameter);
        panelParameter.setLayout(panelParameterLayout);
        panelParameterLayout.setHorizontalGroup(
            panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParameterLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelParameterLayout.createSequentialGroup()
                        .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParameterLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(fieldAlamatDataset))
                            .addGroup(panelParameterLayout.createSequentialGroup()
                                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJudulPanelPatameter)
                                    .addGroup(panelParameterLayout.createSequentialGroup()
                                        .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelParameterLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLajuPem1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelParameterLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jToleKe1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelParameterLayout.createSequentialGroup()
                                                .addComponent(jToleKe2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jToleKe3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelParameterLayout.createSequentialGroup()
                                                .addComponent(jLajuPem2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLajuPem3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelParameterLayout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(buttonOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(buttonReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCari)
                        .addGap(856, 856, 856))))
        );
        panelParameterLayout.setVerticalGroup(
            panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParameterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudulPanelPatameter)
                .addGap(12, 12, 12)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAlamatDataset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCari)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLajuPem1)
                    .addComponent(jLajuPem2)
                    .addComponent(jLajuPem3)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jToleKe1)
                    .addComponent(jToleKe2)
                    .addComponent(jToleKe3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk1)
                    .addComponent(buttonReset1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelUtama.add(panelParameter, "card3");

        panelTitle.setBackground(new java.awt.Color(234, 137, 69));

        labelJudul.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        labelJudul.setText("Aplikasi Ekstraksi Aturan kepuasan Pelanggan Restoran Cepat Saji");

        labelPanelUtama.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelPanelUtama.setForeground(new java.awt.Color(255, 255, 255));
        labelPanelUtama.setText("Panel Utama");

        fieldPetunjukAplikasi.setEditable(false);
        fieldPetunjukAplikasi.setBackground(new java.awt.Color(234, 137, 69));
        fieldPetunjukAplikasi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fieldPetunjukAplikasi.setForeground(new java.awt.Color(255, 255, 255));
        fieldPetunjukAplikasi.setText("Selamat datang! Silahkan tekan tombol parameter untuk memasukan dataset serta parameter pembelajaran");
        fieldPetunjukAplikasi.setBorder(null);
        fieldPetunjukAplikasi.setCaretColor(new java.awt.Color(234, 137, 69));

        buttonParameter.setBackground(new java.awt.Color(113, 127, 50));
        buttonParameter.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonParameter.setForeground(new java.awt.Color(255, 255, 255));
        buttonParameter.setText("Parameter");
        buttonParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonParameterActionPerformed(evt);
            }
        });

        buttonEkstrak.setBackground(new java.awt.Color(113, 127, 50));
        buttonEkstrak.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonEkstrak.setForeground(new java.awt.Color(255, 255, 255));
        buttonEkstrak.setText("Ekstrak");
        buttonEkstrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEkstrakActionPerformed(evt);
            }
        });

        buttonKeluar.setBackground(new java.awt.Color(113, 127, 50));
        buttonKeluar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        buttonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeluar.setText("Keluar");
        buttonKeluar.setToolTipText("");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        labelPetunjukDataset.setBackground(new java.awt.Color(113, 167, 60));
        labelPetunjukDataset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelPetunjukDataset.setForeground(new java.awt.Color(102, 102, 102));
        labelPetunjukDataset.setText("Dataset");

        textFieldDataSet.setBackground(new java.awt.Color(234, 137, 69));
        textFieldDataSet.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldDataSet.setForeground(new java.awt.Color(102, 102, 102));
        textFieldDataSet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDataSet.setText("-");
        textFieldDataSet.setBorder(null);
        textFieldDataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDataSetActionPerformed(evt);
            }
        });

        labelPetunjukLajuPembelajaran.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelPetunjukLajuPembelajaran.setForeground(new java.awt.Color(102, 102, 102));
        labelPetunjukLajuPembelajaran.setText("Laju Pembelajaran");

        textFieldLearningRate.setBackground(new java.awt.Color(234, 137, 69));
        textFieldLearningRate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldLearningRate.setForeground(new java.awt.Color(102, 102, 102));
        textFieldLearningRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldLearningRate.setText("0");
        textFieldLearningRate.setBorder(null);
        textFieldLearningRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLearningRateActionPerformed(evt);
            }
        });

        labelPetunjukMinimumError.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelPetunjukMinimumError.setForeground(new java.awt.Color(102, 102, 102));
        labelPetunjukMinimumError.setText("Toleransi Kesalahan");

        textFieldMinimumError.setBackground(new java.awt.Color(234, 137, 69));
        textFieldMinimumError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textFieldMinimumError.setForeground(new java.awt.Color(102, 102, 102));
        textFieldMinimumError.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldMinimumError.setText("0");
        textFieldMinimumError.setBorder(null);
        textFieldMinimumError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMinimumErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addComponent(fieldPetunjukAplikasi)
                        .addContainerGap())
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addComponent(labelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(741, 741, 741))
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTitleLayout.createSequentialGroup()
                                .addComponent(buttonParameter)
                                .addGap(31, 31, 31)
                                .addComponent(buttonEkstrak)
                                .addGap(31, 31, 31)
                                .addComponent(buttonKeluar))
                            .addGroup(panelTitleLayout.createSequentialGroup()
                                .addComponent(labelPetunjukDataset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPetunjukLajuPembelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPetunjukMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTitleLayout.createSequentialGroup()
                        .addComponent(labelPanelUtama)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelTitleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEkstrak, buttonKeluar, buttonParameter});

        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPanelUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPetunjukAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonParameter)
                    .addComponent(buttonEkstrak)
                    .addComponent(buttonKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPetunjukDataset)
                    .addComponent(textFieldDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPetunjukLajuPembelajaran)
                    .addComponent(textFieldLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPetunjukMinimumError)
                    .addComponent(textFieldMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelTitleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textFieldDataSet, textFieldLearningRate, textFieldMinimumError});

        panelTitleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEkstrak, buttonKeluar, buttonParameter});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        //buttonKeluar.
        System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonParameterActionPerformed
        card.next(panelUtama);
    }//GEN-LAST:event_buttonParameterActionPerformed

    private void textFieldMinimumErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMinimumErrorActionPerformed
        // TODO add your handle
    }//GEN-LAST:event_textFieldMinimumErrorActionPerformed

    private void textFieldLearningRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLearningRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLearningRateActionPerformed

    private void textFieldDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDataSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDataSetActionPerformed

    private void fieldAlamatDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatDatasetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatDatasetActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        alamatFile = null;
        if (evt.getSource() == buttonCari) {
            int returnVal = pemilih.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = pemilih.getSelectedFile();
                //This is where a real application would open the file.
                System.out.println(file.getPath());
                alamatFile = file.getPath();
                fieldAlamatDataset.setText(alamatFile);
            }
        }


        try {
            pembaca = new CSVReader(new FileReader(alamatFile));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PengolahanInput.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            strings = pembaca.readNext();
            String[] namaKolom = new String[strings.length];
            int i = 0;
            for (String nama : strings) {
                namaKolom[i] = nama;
                i++;
            }
            banyakData = 0;
            DftTabMode = new DefaultTableModel(null, namaKolom);
            tabelData.setModel(DftTabMode);
            while ((strings = pembaca.readNext()) != null) {
                DftTabMode.addRow(strings);
                banyakData++;
            }
        } catch (IOException ex) {
            Logger.getLogger(PengolahanInput.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Banyak Data " + banyakData);

    }//GEN-LAST:event_buttonCariActionPerformed

    private void jLajuPem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLajuPem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLajuPem3ActionPerformed
    /*public void tampilTrainingPertama(double[][] input, int[][] target, double[][] output, double epoch, double error){
     textAreaPemPertama.append("Epoch = " + epoch +", Error = "+error );
     for(int i=0;i<input.length;i++){
     textAreaPemPertama.append(
     "Hasil " + output[i][0] + " Target = " + target[i][0] + "||||"
     + output[i][1] + " Target = " + target[i][1]);
     * }
     textAreaPemPertama.append("Method jalan!");
     }*/
    private void buttonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOk1ActionPerformed
        // TODO add your handling code here:

        Enumeration<AbstractButton> radioButtonLR = groupLR.getElements();
        Enumeration<AbstractButton> radioButtonME = groupME.getElements();
        //Mengambil nilai dari radio button learning rate
        while (radioButtonLR.hasMoreElements()) {
            JRadioButton temp = (JRadioButton) radioButtonLR.nextElement();
            if (temp.isSelected()) {
                lr = temp.getText();
                learningRate = Double.parseDouble(lr);
            }
        }
        //Mengambil nilai dari radio button minimum error
        while (radioButtonME.hasMoreElements()) {
            JRadioButton temp = (JRadioButton) radioButtonME.nextElement();
            if (temp.isSelected()) {
                me = temp.getText();
                minimumError = Double.parseDouble(me);
            }
        }

        System.out.println("Learning Rate" + lr);
        System.out.println("Learning Rate" + me);

        /*if(alamatFile != null && !alamatFile.isEmpty()){
         if(me != null && !me.isEmpty()){
         if(lr != null && !lr.isEmpty()){
                    
         }
         }
         }
         else{
         fieldPetunjukAplikasi.setText("");
         }*/
        if (alamatFile != null && !alamatFile.isEmpty() && me != null && !me.isEmpty()) {
            if (lr != null && !lr.isEmpty()) {
                if (me != null && !me.isEmpty()) {
                    textFieldDataSet.setText(alamatFile);
                    textFieldLearningRate.setText(lr);
                    textFieldMinimumError.setText(me);
                    card.next(panelUtama);
                } else {
                    fieldPetunjukAplikasi.setText("Data parameter belum lengkap, silahkan isi kembali.");
                }
            } else {
                fieldPetunjukAplikasi.setText("Data parameter belum lengkap, silahkan isi kembali.");
            }
        } else {
            fieldPetunjukAplikasi.setText("Data parameter belum lengkap, silahkan isi kembali.");
        }



    }//GEN-LAST:event_buttonOk1ActionPerformed

    private void buttonReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReset1ActionPerformed
        // TODO add your handling code here:
        card.next(panelUtama);

    }//GEN-LAST:event_buttonReset1ActionPerformed
    boolean cekParameter() {
        if (alamatFile != null && !alamatFile.isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    private void buttonEkstrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEkstrakActionPerformed
        if (cekParameter() == false) {
            fieldPetunjukAplikasi.setText("Ekstraksi belum bisa dilakukan, silahkan isi parameter dan dataset terlebih dahulu.");
        } else {
            PengolahanInput objekInput = new PengolahanInput();
            NeuralNetwork objekNN = new NeuralNetwork();
            PruningClustering objekPC = new PruningClustering();
            fieldPetunjukAplikasi.setText("Ekstraksi dilakukan!");

            objekInput.parsingInput(alamatFile, banyakData);
            double[][] input = objekInput.dataInput();
            int[][] target = objekInput.target();
            objekNN.mainNN(input, target, learningRate, minimumError);
            double[][] keluaranPertama = objekNN.giveOutput();
            //Tampil Hasil Pembelajaran Pertama
            textFieldTotalEpoch.setText("Total Epoch = " + objekNN.getEpoch() + " Error = " + objekNN.error() + "\n");
            textAreaPemPertama.append("Keluaran : " + "\n");
            for (i = 0; i < keluaranPertama.length; i++) {
                textAreaPemPertama.append("Target = " + target[i][0] + ", Hasil = " + keluaranPertama[i][0] + " || "
                        + "Target = " + target[i][1] + ", Hasil = " + keluaranPertama[i][1] + "\n");
            }


            //Pruning
            double[][] weightInput = objekNN.giveWeightInput();
            double[][] weightOutput = objekNN.giveWeightOutput();
            double[][] weightBias = objekNN.giveWeightBias();
            double threshold = objekNN.minDC();

            objekPC.pruning(weightInput, weightOutput, threshold);
            //Hasil Pruning
            ArrayList<ArrayList<Integer>> lostNeuron = objekPC.lostNeuron();
            ArrayList<ArrayList<Integer>> indexNotLost = objekPC.notLostNeuron();
            ArrayList<Integer> indexExclude = objekPC.lostExclude();
            ArrayList<ArrayList<Integer>> indexNeuron = objekPC.indexNeuron();

            objekInput.inputTargetDiscretize2(input, indexNotLost, target);
            ArrayList<ArrayList<Double>> inputBaru = objekInput.inputBaru();
            ArrayList<ArrayList<Integer>> targetBaru = objekInput.targetBaru();

            //Display Hasil
            textFieldPruning1.setText("Jumlah pattern exclude = " + indexExclude.size() + "\n");
            textFieldPruning2.setText("Jumlah pattern include = " + indexNotLost.size() + "\n");
            textFieldPruning3.setText("Jumlah pattern Lost = " + lostNeuron.size() + "\n");

            for (i = 0; i < lostNeuron.size(); i++) {
                textAreaPruning.append("Pattern ke - " + i + "\n");
                textAreaPruning.append("Lost = " + lostNeuron.get(i) + " Not Lost = "
                        + indexNeuron.get(i) + "\n");
            }
            for (i = 0; i < targetBaru.size(); i++) {
                textAreaPruning.append("Pattern ke - " + i + "\n");
                textAreaPruning.append("Input = " + inputBaru.get(i) + " Target = "
                        + targetBaru.get(i) + "\n");
            }

            //Pembelajaran Kedua setelah pangkas neuron
            objekNN.NNDiscretizing(inputBaru, targetBaru, learningRate, minimumError);
            double[] nInputLayer = objekNN.giveOutputHidden2();
            double[][] bobotOutput = objekNN.giveBobotOutput();
            double[][] bobotBias = objekNN.giveBobotBias();
            double[][] output2 = objekNN.giveOutput3();

            for (double isi : nInputLayer) {
                textAreaNilaiAktivasi.append(String.valueOf(isi) + "\n");
            }
            for (i = 0; i < bobotBias.length; i++) {
                textAreaBobotBias.append("Patern ke - " + i + " = "
                        + String.valueOf(bobotBias[i][0]) + ","
                        + String.valueOf(bobotBias[i][1]) + ","
                        + String.valueOf(bobotBias[i][2]) + "\n");
            }
            for (i = 0; i < bobotOutput.length; i++) {
                textAreaBobotOutput.append("Patern ke - " + i + " = "
                        + String.valueOf(bobotOutput[i][0]) + ","
                        + String.valueOf(bobotOutput[i][1]) + "," + "\n");
            }
            for (i = 0; i < inputBaru.size(); i++) {
                textAreaPemKedua.append("Pattern ke - " + i + " = " + inputBaru.get(i) + ","
                        + "Target = " + targetBaru.get(i).get(0) + ", Hasil = " + output2[i][0] + " || "
                        + "Target = " + targetBaru.get(i).get(1) + ", Hasil = " + output2[i][1] + "\n");
            }

            double[] nDiscretize = objekPC.doDiscretize(0.1, nInputLayer);
            //List<Double> nilaiPerCluster = objekPC.returnNilaiCluster();
            List<Double> nilaiPerCluster = objekPC.nilaiPerCluster(nDiscretize);
            objekPC.clustering(nDiscretize);
            ArrayList<ArrayList<Integer>> terurut = objekPC.getTerurut();
            textAreaDiscretize.append("Banyak Cluster = " + nilaiPerCluster.size() + "\n");
            textAreaDiscretize.append("Nilai - Nilai Cluster = " + nilaiPerCluster + "\n");
            textAreaDiscretize.append("\n");

            for (i = 0; i < terurut.size(); i++) {
                textAreaDiscretize.append("Cluster ke - " + i + " = " + terurut.get(i) + "\n");
            }

            double nErrorDiscre = objekNN.mainNN(nDiscretize, bobotOutput, bobotBias, targetBaru);
            double[][] outputDiscre = objekNN.giveOutput2();

            textAreaPemDiscretize.append("Hasil Clustering" + "\n");
            textAreaPemDiscretize.append("Error = " + nErrorDiscre + "\n");
            for (i = 0; i < nDiscretize.length; i++) {
                textAreaPemDiscretize.append("Node ke - " + i
                        + "Nilai Discretizing = " + String.valueOf(nDiscretize[i])
                        + " Output = " + String.valueOf(outputDiscre[i][0])
                        + " Target  = " + String.valueOf(targetBaru.get(i).get(0))
                        + " Output  = " + String.valueOf(outputDiscre[i][1])
                        + " Target  = " + String.valueOf(targetBaru.get(i).get(1)) + "\n");
            }

            EkstraksiAturan objekEkstrak = new EkstraksiAturan();
            objekEkstrak.ekstraksiGreedy(indexNotLost, terurut, inputBaru, targetBaru);
            ArrayList<Integer> hasil = objekEkstrak.getIdxHasil();

            for(i=0;i<hasil.size();i++){
               int a = i+1; 
               textAreaAturan.append(" Aturan ke - "+a+"\n"); 
               for(n=1;n<indexNotLost.get(hasil.get(i)).size();n++){
                int atribut = indexNotLost.get(hasil.get(i)).get(n);
                if( atribut == 0){
                    textAreaAturan.append(" Rasa = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Enak ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Kurang Enak ");
                            } else {
                                textAreaAturan.append(" Enak ");
                            }
                }
                else if(atribut == 1){
                    textAreaAturan.append(" Porsi = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Kurang ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Lebih ");
                            } else {
                                textAreaAturan.append(" Pas ");
                            }
                }
                else if(atribut ==2){
                      textAreaAturan.append(" Dessert = ");
                           if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Enak ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append("Kurang Enak ");
                            } else {
                                textAreaAturan.append(" Enak ");
                            }
                }
                else if(atribut ==3){
                    textAreaAturan.append(" Suasana Restoran = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Nyaman ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Kurang Nyaman ");
                            } else {
                                textAreaAturan.append(" Nyaman ");
                            }
                }
                else if(atribut == 4){
                    textAreaAturan.append(" Washtupple = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Bersih ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Kurang Bersih ");
                            } else {
                                textAreaAturan.append(" Bersih ");
                            }
                }
                else if(atribut == 5){
                    textAreaAturan.append(" Penyajian Makanan = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Lambat ");
                            } else {
                                textAreaAturan.append(" Cepat ");
                            }
                }
                else if(atribut == 6){
                    textAreaAturan.append(" Perilaku Staff = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Ramah ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Kurang Ramah");
                            } else {
                                textAreaAturan.append(" Ramah ");
                            }
                }
                else if(atribut == 7){
                    textAreaAturan.append(" Harga = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Mahal ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Normal ");
                            } else {
                                textAreaAturan.append(" Diskon ");
                            }
                }
                else if(atribut == 8){
                    textAreaAturan.append(" Diskon = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak ");
                            } else {
                                textAreaAturan.append(" Ya ");
                            }
                }
                else{
                    textAreaAturan.append(" Lokasi = ");
                    if (inputBaru.get(hasil.get(i)).get(n-1) == 0) {
                                textAreaAturan.append(" Tidak Strategis ");
                            } else if (inputBaru.get(hasil.get(i)).get(n-1) == 0.5) {
                                textAreaAturan.append(" Kurang Strategis ");
                            } else {
                                textAreaAturan.append(" Strategis ");
                            }
                }
               }
               textAreaAturan.append(" Pelanggan Puas");
               textAreaAturan.append("\n"); 
            }
            textAreaAturan.append(" Default : Pelanggan Tidak Puas");
            System.out.println("Hasil di firstUI = " + hasil);
            System.out.println(inputBaru.get(hasil.get(0)));
            System.out.println(indexNotLost.get(hasil.get(0)));
            /*System.out.println(indexNotLost.get(hasil.get(0)));
             System.out.println(inputBaru.get(hasil.get(0)));*/

            //Ekstraksi
            /*RuleExtraction objekRule = new RuleExtraction();
             objekRule.getPuas(terurut,targetBaru);
             ArrayList<ArrayList<Integer>> terurutBersih = objekRule.getTerurutBersih();
             int banyak = 0;
             textAreaAturan.append("Cluster Bersih \n");
             for(i =0;i<terurutBersih.size();i++){
             textAreaAturan.append(terurutBersih.get(i)+"\n");
             banyak += terurutBersih.get(i).size();
             }
             textAreaAturan.append("Jumlah Pattern = "+banyak+"\n");
            
             objekRule.removeLongRule(inputBaru);
             terurutBersih = objekRule.getTerurutBersih();
             banyak = 0;
             textAreaAturan.append("Hasil Pruning Cluster \n");
             for(i =0;i<terurutBersih.size();i++){
             textAreaAturan.append(terurutBersih.get(i)+"\n");
             banyak += terurutBersih.get(i).size();
             }
             textAreaAturan.append("Jumlah Pattern = "+banyak+"\n");
             */
            /*objekRule.removeSpesificWithGeneral(inputBaru);
             terurutBersih = objekRule.getTerurutBersih();
             textAreaAturan.append("Hasil Pengurutan  \n");
             for(i =0;i<terurutBersih.size();i++){
             textAreaAturan.append(terurutBersih.get(i)+"\n");
             banyak += terurutBersih.get(i).size();
             }*/
            /*for(i =0; i<terurutBersih.size();i++){
             for(m=0;m<terurutBersih.get(i).size();m++){
             textAreaAturan.append(inputBaru.get(terurutBersih.get(i).get(m))+"\n");
             }
             textAreaAturan.append("\n");
             }*/

            /*ArrayList<Integer> jumlah = objekRule.getJumlah();
             textAreaAturan.append(String.valueOf(jumlah));*/
        }
    }//GEN-LAST:event_buttonEkstrakActionPerformed
    public void display() {
        new FirstUI().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FirstUI objek = new FirstUI();
                objek.display();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Discretizing;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonEkstrak;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonOk1;
    private javax.swing.JButton buttonParameter;
    private javax.swing.JButton buttonReset1;
    private javax.swing.JTextField fieldAlamatDataset;
    private javax.swing.JTextField fieldPetunjukAplikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLajuPem1;
    private javax.swing.JRadioButton jLajuPem2;
    private javax.swing.JRadioButton jLajuPem3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JRadioButton jToleKe1;
    private javax.swing.JRadioButton jToleKe2;
    private javax.swing.JRadioButton jToleKe3;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudulPanelEkstrak;
    private javax.swing.JLabel labelJudulPanelPatameter;
    private javax.swing.JLabel labelPanelUtama;
    private javax.swing.JLabel labelPetunjukDataset;
    private javax.swing.JLabel labelPetunjukLajuPembelajaran;
    private javax.swing.JLabel labelPetunjukMinimumError;
    private javax.swing.JPanel panelAturan;
    private javax.swing.JPanel panelDiscretizing;
    private javax.swing.JPanel panelPangkasNeuron;
    private javax.swing.JPanel panelParameter;
    private javax.swing.JPanel panelPemKedua;
    private javax.swing.JPanel panelPemPertama;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTrainingEkstrak;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextArea textAreaAturan;
    private javax.swing.JTextArea textAreaBobotBias;
    private javax.swing.JTextArea textAreaBobotOutput;
    private javax.swing.JTextArea textAreaDiscretize;
    private javax.swing.JTextArea textAreaNilaiAktivasi;
    private javax.swing.JTextArea textAreaPemDiscretize;
    private javax.swing.JTextArea textAreaPemKedua;
    private javax.swing.JTextArea textAreaPemPertama;
    private javax.swing.JTextArea textAreaPruning;
    private javax.swing.JTextField textFieldDataSet;
    private javax.swing.JTextField textFieldLearningRate;
    private javax.swing.JTextField textFieldMinimumError;
    private javax.swing.JTextField textFieldPruning1;
    private javax.swing.JTextField textFieldPruning2;
    private javax.swing.JTextField textFieldPruning3;
    private javax.swing.JTextField textFieldTotalEpoch;
    // End of variables declaration//GEN-END:variables
}
